/**
 * Tiny build script: concatenates src/ modules into the single lib/client.js
 * bundle the client-modules pipeline serves at /plugins/<id>/client.js.
 *
 * The shipped client bundles are single files whose factory bodies share one
 * scope (tsdown output convention); this script reproduces that shape for a
 * hand-written plugin — no external toolchain required. Run: `node build.js`.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(fileURLToPath(import.meta.url));
const SRC = ["css.js", "diag.js", "util.js", "guard.js", "view.js", "markdown.js", "commands.js", "components.js", "preview.js", "plugin.js"];
const PLUGIN_ID = "@dsh-local/ui-terminal";

const banner = `/**
 * ${PLUGIN_ID} client bundle (GENERATED by build.js from src/ — do not edit).
 * Loaded by the shell kernel as a lazy-CJS module; see src/*.js for sources.
 */
window.__ModuleLoader__.load({
\tid: ${JSON.stringify(PLUGIN_ID)},
\tfactory: (require) => {
\t\tvar module = { exports: {} };
\t\tvar exports = module.exports;
\t\tObject.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
\t\tlet react = require("react");
\t\tlet react_jsx_runtime = require("react/jsx-runtime");
\t\tlet _web_react = require("@deepseek-ai/dsh-client-web-react");
\t\tlet bindSnapshotSelector = _web_react.bindSnapshotSelector;
`;

const footer = `\t\texports.apply = apply;
\t\texports.inject = inject;
\t\texports.mount = mount;
\t\texports.unmount = unmount;
\t\texports.termGuard = termGuard;
\t\treturn module.exports;
\t}
});

//# sourceMappingURL=client.js.map
`;

const body = SRC.map((file) => {
  const code = readFileSync(join(ROOT, "src", file), "utf8").replace(/\r\n/g, "\n");
  return `\t\t//#region src/${file}\n${indent(code, "\t\t")}\n\t\t//#endregion`;
}).join("\n");

function indent(text, pad) {
  return text
    .split("\n")
    .map((line) => (line === "" ? line : pad + line))
    .join("\n");
}

const out = banner + body + "\n" + footer;
const outPath = join(ROOT, "lib", "client.js");
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, out);
console.log(`wrote ${outPath} (${out.length} bytes)`);
